export { HomePage } from './HomePage'
export { AddSongPage } from './AddSongPage'
export { SongDetailPage } from './SongDetailPage'
export { EditSongPage } from './EditSongPage'
export { TagManagePage } from './TagManagePage'
export { LoginPage } from './LoginPage'
